switched from port 8000 to 8081 in yaml pipelines

diff --git a/.github/workflows/build-and-deploy.yaml b/.github/workflows/build-and-deploy.yaml
--- a/.github/workflows/build-and-deploy.yaml
+++ b/.github/workflows/build-and-deploy.yaml
@@ -108,10 +108,10 @@ jobs:
             PORT=$(grep -oE '--port[= ]*[0-9]+' Dockerfile | head -n1 | sed -E 's/[^0-9]*([0-9]+).*/\1/' || true)
           fi
 
-          # 3) Fallback to default 8000
+          # 3) Fallback to default 8081
           if [ -z "$PORT" ]; then
-            echo "No EXPOSE or --port found in Dockerfile; defaulting to 8000"
-            PORT=8000
+            echo "No EXPOSE or --port found in Dockerfile; defaulting to 8081"
+            PORT=8081
           fi
 
           echo "Checking port: $PORT"
@@ -153,13 +153,13 @@ jobs:
           # Remove any existing previous leftovr containers
           docker rm -f "$NAME" || true
           # Now, run the new container
-          docker run -d --name "$NAME" --label gh_workflow=video2text --restart unless-stopped -p 8000:8000 --env-file .env.ci ${{ env.IMAGE_NAME }}:latest
+          docker run -d --name "$NAME" --label gh_workflow=video2text --restart unless-stopped -p 8081:8081 --env-file .env.ci ${{ env.IMAGE_NAME }}:latest
           echo "CONTAINER_NAME=$NAME" >> $GITHUB_ENV    
 
       - name: Healthcheck                                        # because the container was started detached, we should check that the service started properly
         run: |
           for i in $(seq 1 20); do
-            status=$(curl -s -o /tmp/resp -w "%{http_code}" http://localhost:8000/docs || echo "000")
+            status=$(curl -s -o /tmp/resp -w "%{http_code}" http://localhost:8081/docs || echo "000")
             if [ "$status" = "200" ]; then
               echo "health ok"
               exit 0
@@ -170,7 +170,7 @@ jobs:
           docker logs --tail 200 "$CONTAINER_NAME" || true
           exit 1
 
-#      - name: Cleanup (optional) 
+#      - name: Cleanup (optional) (kill container) 
 #        if: always()
 #        run: |
 #          docker stop "$CONTAINER_NAME" || true
